name: frankenphp-symfony-lab

x-healthcheck: &healthcheck
  test: ["CMD", "php", "-r", "exit(false === @file_get_contents('http://localhost/health') ? 1 : 0);"]
  interval: 10s
  timeout: 3s
  retries: 3
  start_period: 10s

services:
  php-demo:
    image: dunglas/frankenphp:1-php8.5-bookworm
    network_mode: bridge
    environment:
      SERVER_NAME: :80
    ports:
      - "8282:80"
    volumes:
      - ./franken-test/public:/app/public:ro
      - ./docker/frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
    healthcheck: *healthcheck
    tty: true

  symfony-classic:
    image: dunglas/frankenphp:1-php8.5-bookworm
    network_mode: bridge
    working_dir: /app
    environment:
      SERVER_NAME: :80
      APP_ENV: dev
      DEMO_MODE: classique
    ports:
      - "8384:80"
    volumes:
      - ./franken-symfony:/app
      - ./docker/frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
    healthcheck: *healthcheck
    tty: true

  symfony-worker:
    image: dunglas/frankenphp:1-php8.5-bookworm
    network_mode: bridge
    working_dir: /app
    environment:
      SERVER_NAME: :80
      APP_ENV: dev
      DEMO_MODE: worker
      FRANKENPHP_CONFIG: |
        worker {
          file ./public/index.php
          num 10
          watch
        }
    ports:
      - "8385:80"
    volumes:
      - ./franken-symfony:/app
      - ./docker/frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
    healthcheck: *healthcheck
    tty: true
